#!/data/data/com.termux/files/usr/bin/bash
# SPDX-License-Identifier: Apache-2.0
# This file is part of termux-container.
#
# Copyright (c) 2023 Moe-hacker
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
############################
if [[ ! -e $PREFIX/share/termux-container/licenses.allowed ]];then
  x="
  Copyright (c) 2021-2023 Moe-hacker

 Licensed under the Apache License, Version 2.0 (the \"License\");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an \"AS IS\" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 Make sure you have already read the license, and you agree with ALL OF THEM.
 Now you can press CTRL-C to exit
 or agree with THE LICENSE and :
 Press Enter to continue.
  "
  printf "${x}"
  read x
  touch $PREFIX/share/termux-container/licenses.allowed
  clear
fi
if [[ ! -e ~/.termux/font.ttf ]];then
  echo -e "Installing fonts....."
  wget https://github.com/Moe-hacker/termux-container/raw/main/src/usr/share/termux-container/font.ttf -O ~/.termux/font.ttf||wget https://kgithub.com/Moe-hacker/termux-container/raw/main/src/usr/share/termux-container/font.ttf -O ~/.termux/font.ttf||exit 1
  termux-reload-settings
fi
if [[ ! -e ~/.termux/colors.properties ]];then
  echo -e "Installing color settings....."
  wget https://github.com/Moe-hacker/termux-container/raw/main/src/usr/share/termux-container/colors.properties -O ~/.termux/colors.properties||wget https://kgithub.com/Moe-hacker/termux-container/raw/main/src/usr/share/termux-container/colors.properties -O ~/.termux/colors.properties||exit 1
  termux-reload-settings
fi
