#!/bin/sh
#
# SPDX-License-Identifier: Apache-2.0
# This file is part of termux-container.
#
# Copyright (c) 2023 Moe-hacker
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
mount -t proc proc -o rw,nosuid,nodev,noexec,relatime /proc 2>&1 >/dev/null
mount -t sysfs sysfs -o ro,seclabel,nosuid,nodev,noexec,relatime /sys 2>&1 >/dev/null
mount -t tmpfs tmpfs -o rw,seclabel,nosuid,size=65536k,mode=755 /dev 2>&1 >/dev/null
mknod -m 622 /dev/console c 5 1 2>&1 >/dev/null
chown root:tty /dev/console 2>&1 >/dev/null
rm /dev/null
mknod -m 666 /dev/null c 1 3 2>&1 >/dev/null
mknod -m 666 /dev/zero c 1 5 2>&1 >/dev/null
mknod -m 666 /dev/ptmx c 5 2 2>&1 >/dev/null
chown root:tty /dev/ptmx 2>&1 >/dev/null
mknod -m 666 /dev/tty c 5 0 2>&1 >/dev/null
chown root:tty /dev/tty 2>&1 >/dev/null
mknod -m 444 /dev/random c 1 8 2>&1 >/dev/null
mknod -m 444 /dev/urandom c 1 9 2>&1 >/dev/null
ln -s /proc/self/fd /dev/fd 2>&1 >/dev/null
ln -s /proc/self/fd/0 /dev/stdin 2>&1 >/dev/null
ln -s /proc/self/fd/1 /dev/stdout 2>&1 >/dev/null
ln -s /proc/self/fd/2 /dev/stderr 2>&1 >/dev/null
ln -s /dev/null /dev/tty0 2>&1 >/dev/null
mkdir /dev/pts 2>&1 >/dev/null
mount -t devpts -o gid=4,mode=620 devpts /dev/pts 2>&1 >/dev/null
mkdir /dev/shm 2>&1 >/dev/null
mount -o rw,nosuid,nodev,mode=1777 -t tmpfs tmpfs /dev/shm 2>&1 >/dev/null
mkdir /dev/mqueue 2>&1 >/dev/null
mount -t mqueue none /dev/mqueue 2>&1 >/dev/null
mkdir /dev/net 2>&1 >/dev/null
mknod /dev/net/tun c 10 200 2>&1 >/dev/null
mount -o bind,private,ro /proc/sysrq-trigger /proc/sysrq-trigger 2>&1 >/dev/null
mount -o bind,ro,relatime /proc/bus /proc/bus
mount -o bind,ro,relatime /proc/fs /proc/fs
mount -o bind,ro,relatime /proc/irq /proc/irq
mount -o bind,ro,relatime /proc/sys /proc/sys
mount -o bind,ro,seclabel,relatime /proc/asound /proc/asound
mount -o bind,ro,seclabel,relatime /proc/scsi /proc/scsi
mount -o bind,ro,seclabel,relatime /sys/firmware /sys/firmware
if [ $(hostname) != $(cat /etc/hostname) ]; then
  hostname $(cat /etc/hostname) 2>&1 >/dev/null
fi
rm /dev/null && mknod -m 666 /dev/null c 1 3
printf "\033[0m"
/bin/su - root
